### ISSUE TITLE
站内很多图片都挂了

### ISSUE THREAD

**Issue by skywalk163** [lisniuse/numpy-cn#27]
项目中大部分图片都挂了，比如随便翻开一页：https://www.numpy.org.cn/deep/basics/fit_a_line.html#%E6%95%88%E6%9E%9C%E5%B1%95%E7%A4%BA

里面的图片1就没有显示，图片位置：https://github.com/PaddlePaddle/book/blob/develop/01.fit_a_line/image/predictions.png?raw=true

建议图片还是放在本github比较好。

ps ，本项目github首页https://github.com/teadocs/numpy-cn的logo图片都挂了。

**Comment by lisniuse** [comment]
收到！今天内处理好。

**Comment by skywalk163** [comment]
我用的是移动的线路，现在看还是挂的。

比如随便找一个图片：
页面：https://www.numpy.org.cn/deep/basics/fit_a_line.html#%E8%83%8C%E6%99%AF%E4%BB%8B%E7%BB%8D
里面的“背景介绍”那段里面的一个图片：
图片地址是 ：https://raw.githubusercontent.com/PaddlePaddle/book/develop/01.fit_a_line/image/formula_fit_a_line_1.png

连接的时候显示：
raw.githubusercontent.com 拒绝了我们的连接请求。

2020.5.11日更新：
看到网上的解决方法，增加了相应的域名解析，图片都ok了！
比如这样的域名解析：
151.101.184.133    raw.githubusercontent.com


看来是dns（咱也不知道是污染，还是咋的事）的问题。以前可能是指向13.229.188.59这个地址的。
