### ISSUE TITLE
“快速入门”章节中Numpy文档的跳转问题

### ISSUE THREAD

**Issue by super233** [lisniuse/numpy-cn#8]
在“快速入门”章节中，所有Numpy方法的文档链接跳转有问题，点击后，URL前面增加了多余的内容，从而导致跳转失败。
![Snipaste_2019-10-10_16-36-35](https://user-images.githubusercontent.com/35358984/66552558-27efa680-eb7c-11e9-9979-140e4e21717d.png)

**Comment by lisniuse** [comment]
现在还有这个问题吗？

**Comment by super233** [comment]
还存在这个问题，辛苦开发者了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ZhiBing(陈治兵)"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月12日(星期二) 上午10:55
收件人:&nbsp;"teadocs/numpy-cn"<numpy-cn@noreply.github.com&gt;;
抄送:&nbsp;"唐文琦"<393196531@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [teadocs/numpy-cn] “快速入门”章节中Numpy文档的跳转问题 (#8)




现在还有这个问题吗？

**Comment by lisniuse** [comment]
好了，发布到线上了。
